### ISSUE TITLE
Parameter Skin Settings

### ISSUE THREAD

**Issue by adrienturpin974** [hawkeyexp/Kodi-Repository-Nextgen#1]
Hello,

The skin parameters (button) are not saved at startup, it returns by default

Adrien TURPIN.

**Comment by hawkeyexp** [comment]
Hi, i have checked it again and no problems with lost button mappings
caused by unwritten strings. You should make sure kodi exits clean and is
not aborted via prozess for example. When kodi is not exited clean it
sometimes won't write its last set strings so it could happen.

Next update will be available this evening i think :-)

2016-11-30 16:04 GMT+01:00 adrienturpin974 <notifications@github.com>:

**Comment by adrienturpin974** [comment]
It's work now =)
